### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pigbrother**
I have used this plugin, but I have been reporting errors under netcore. Do I need to refer to other DLLS?
Exception :
   Exception from HRESULT: 0x8007000B
   System.Data.OracleClient.Oci.OciCalls+OciNativeCalls.OCIEnvCreate(out IntPtr envhpp, OciEnvironmentMode mode, IntPtr ctxp, IntPtr malocfp, IntPtr ralocfp, IntPtr mfreep, int xtramem_sz, IntPtr usrmempp)

### CODE REVIEW

**Comment by tonyrapozo** [comment]
Hi @pigbrother . 
You need the oracle's client lib to get system running.
Are they installed?

**Comment by pigbrother** [comment]
Hi @tonyrapozo 
Thank you very much for your reply.
You have already installed win32_oracle_client or not, which one do you mean by oracle's client lib?Is there a download address?
I am a Windows server server and windos development environment

**Comment by pigbrother** [comment]
@tonyrapozo win32_11gR2_client

**Comment by tonyrapozo** [comment]
@pigbrother.
Can you open an issue with your environment and full callstack of error?
So, we can resolve there.
I'll reject this PR and comment in your issue.

**Pull request closed without merging**
